# Generated by Django 2.2.2 on 2019-06-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='establishment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Establishment Date'),
        ),
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colleges_pics/'),
        ),
    ]
